name: cicd pipeline

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - 'feature/*'

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.upload-artifact.outputs.artifact-path }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build Project
        run: mvn clean install -DskipTests=true

      - name: Upload Build Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Run Unit Tests
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SHIELD_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SHIELD_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SHIELD_PASSWORD }}
          SPRING_DATASOURCE_DRIVER_CLASSNAME: com.mysql.cj.jdbc.Driver
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_VALIDITY: ${{ secrets.JWT_VALIDITY }}

